### ISSUE TITLE
Library Usage

### ISSUE THREAD

**Issue by jhaydaman** [awestlake87/pyo3-asyncio#13]
I'm writing a library in Rust that I want to call from Python, and I'm a bit confused on how to handle the rust event loop? pyo3_asyncio panics with `PyO3 Asyncio has not been initialized` unless `try_init()` is called. But the only public function that calls `try_init()` is `with_runtime()`. `with_runtime()` has the side effect of stopping the Python-side event loop when the function completes, so that's not at all what I want.

I've changed `try_init()` to be public so that I can call it when I import my module like this

```rust
#[pymodule]
fn my_module(py: Python, module: &PyModule) -> PyResult<()> {
    pyo3_asyncio::tokio::init_multi_thread();
    pyo3_asyncio::try_init(py)?;
    // rest of my module
    Ok(())
}
```

This seems to work from Python just fine. I can import and call async functions, run them concurrently with Python async functions, and do cpu-bound work on the rust side without interrupting anything. Can/should `try_init()` be public and used in this way, or am I missing some problem with doing things like this or an alternate approach?

**Comment by awestlake87** [comment]
Yeah, that seems reasonable to me. The only real reason it's private is that I didn't know of a use-case for it outside of `with_runtime` at the time. It might also be a good idea to expose the `close` fn (I think that's what it's called), for a graceful tear-down as well, although I'm not sure if it's necessary in your case. 

This could be a patch release, so I'd be willing to fix and release it in a few days unless anyone has any objections.

**Comment by awestlake87** [comment]
The only caveat right now is that if you have two modules that call `try_init`, this could be problematic currently. I think I can fix this by making `try_init` a no-op if it's already been called, which seems fairly straightforward.

**Comment by awestlake87** [comment]
I made some changes in #14 that should fix your issue.

I think your example will look like this after the new changes:
```rust
#[pymodule]
fn my_module(py: Python, module: &PyModule) -> PyResult<()> {
    pyo3_asyncio::tokio::init_multi_thread_once();
    pyo3_asyncio::try_init(py)?;
    // rest of my module
    Ok(())
}
```

**Comment by jhaydaman** [comment]
Thanks, it's working for me.

**Comment by awestlake87** [comment]
Awesome! I'm most likely going to try and release these changes today. Sorry for the delay!
