### ISSUE TITLE
Support using other python event loop?

### ISSUE THREAD

**Issue by WindSoilder** [awestlake87/pyo3-asyncio#16]
Refer to this:
***In the future, more runtimes may be supported for Rust.*** (from https://docs.rs/pyo3-asyncio/0.13.3/pyo3_asyncio/#rusts-event-loop)

I wonder if it support using other executor in asyncio? like [uvloop](https://github.com/MagicStack/uvloop), we can use it through [setting asyncio event loop policy](https://github.com/MagicStack/uvloop/blob/master/uvloop/__init__.py#L25)

### Why it maybe useful?
It's just my guess:

Because we keep both `python` and `rust` event loop, if we have a higher performance `python event loop`,  the whole program can be speeded up too.

**Comment by awestlake87** [comment]
I think this is possible already, but you'll have to set the `asyncio` event loop policy to `uvloop` _before_ `pyo3-asyncio` is initialized. Internally, we call `asyncio.get_event_loop` to perform some setup and cleanup for the Python event loop, but _I think_ that function should return `uvloop` if the policy has been switched beforehand.

Assuming your entrypoint is a Rust main function like the example in #15, you'll need to expand the `#[pyo3_asyncio::tokio::main]` attribute for some custom initialization:

> Disclaimer: I haven't actually tried this, so it might have some problems
```rust
fn main() {
    async fn main() -> PyResult<()> {
        // your application code starts here
    }

    // manually initialize tokio to multi-threaded runtime
    pyo3_asyncio::tokio::init(
        pyo3_asyncio::tokio::re_exports::runtime::Builder::new_multi_thread()
                .enable_all()
                .build()
                .unwrap()
    );

    pyo3::Python::with_gil(|py| {
        // change the Python event loop policy to uvloop
        let uvloop = py.import("uvloop")?;
        uvloop.call_method0("install")?;

        pyo3_asyncio::with_runtime(py, || {
            pyo3_asyncio::tokio::run_until_complete(py, main())?;
            Ok(())
        })
        .map_err(|e| {
            e.print_and_set_sys_last_vars(py);
        })
        .unwrap();
    });
}
```

Sorry it's a bit ugly, but if this works for you, it might be worthwhile for us to create some convenience functions to clean this process up a bit.

**Comment by WindSoilder** [comment]
Thanks :-) It works, I have tried this and query for event loop inside `nested main`, and it returns back I'm using `uvloop.EventLoopPolicy`, Here is updated code snippet:

```rust
use pyo3::prelude::*;

// remove the #[pyo3_asyncio::tokio::main] attribute and change your entrypoint to this:
fn main() -> PyResult<()> {
    async fn main() -> PyResult<()> {
        Python::with_gil(|py| {
            let asyncio = py.import("asyncio").unwrap();
            let res = asyncio.call_method0("get_event_loop_policy").unwrap();
            println!("{:?}", res);
        });
        Ok(())
    }

    // manually initialize tokio to multi-threaded runtime
    pyo3_asyncio::tokio::init_multi_thread();

    pyo3::Python::with_gil(|py| {
        // change the Python event loop policy to uvloop
        let uvloop = py.import("uvloop")?;
        uvloop.call_method0("install")?;

        // drive the async main fn to completion
        pyo3_asyncio::with_runtime(py, || {
            pyo3_asyncio::tokio::run_until_complete(py, main())?;
            Ok(())
        })
        .map_err(|e| {
            e.print_and_set_sys_last_vars(py);
        })
        .unwrap();

        Ok(())
    })
}
```

But sadly I find the performance is not as good as `using python code directly`

Just my guess....

is it mainly because the costs is high(like acquire python gil, transfer data between python side and rust side) when we try to `call python function from rust`?

**Comment by awestlake87** [comment]
I can't really say for sure what's causing the performance problems without more information, but I would assume that the problem lies with transferring data between Rust and Python.

There is definitely some room to improve the performance of this library (and the `into_stream` snippet as well), but I'm not sure it'll be enough to get the results you're looking for.

If you're able to share your code, I can take a look and see what I think!

**Comment by WindSoilder** [comment]
Sure, I think it's better to fired another issue, I paste code there: https://github.com/awestlake87/pyo3-asyncio/issues/18
