### ISSUE TITLE
Python async function not completing when being awaited from rust

### ISSUE THREAD

**Issue by sansyrox** [awestlake87/pyo3-asyncio#20]
```
//lib.rs

#[pyclass]
struct Server {}

#[pymethods]
impl Server {
    #[new]
    fn new() -> Self {
        Self {}
    }

    fn start(mut self_: PyRefMut<Self>, test: &PyAny) {


        let f = pyo3_asyncio::into_future(test);
        let rt = tokio::runtime::Runtime::new().unwrap();
        rt.spawn(async {
            let x = f.unwrap().await;
            match &x {
                Ok(_) => (),
                Err(v) => println!("{}", v),
            }
        });
    }
}

#[pymodule]
pub fn roadrunner(py: Python<'_>, m: &PyModule) -> PyResult<()> {
    m.add_class::<Server>()?;
    pyo3_asyncio::try_init(py);
    Ok(())
}

```

```
import rust_package

async def h():
    print("message from coroutine")


print("Hello world")
s = rust_package.Server()
s.start(h)

```

Above are my rust and  my python files. But when I am trying to spawn and await an async python function from rust, I am not getting any response as if the function is not being completed. How can I await this/complete this function in rust?

Thanks in advance 😄

**Comment by sansyrox** [comment]
Also, is there some way I could await it in the tokio runtime only and not create another python async loop like I have done in the pymodule function.

**Comment by sansyrox** [comment]
I did some more reading in the library and tried a different approch of the start function 

```
    fn start(mut self_: PyRefMut<Self>, test: &PyAny) {
        let f = pyo3_asyncio::into_future(test).unwrap();
        let rt = tokio::runtime::Runtime::new().unwrap();
        pyo3_asyncio::tokio::init(rt);
        Python::with_gil(|py| {
            pyo3_asyncio::tokio::run_until_complete(py, async move {
                tokio::time::sleep(Duration::from_secs(1)).await;
                f.await.unwrap();
                Ok(())
            })
            .unwrap();
        });
}
```

Now I am getting the following error:

```
Hello world
Exception in callback <builtins.PyEnsureFuture object a
t 0x10bc1bd20>()
handle: <Handle <builtins.PyEnsureFuture object at 0x10
bc1bd20>()>
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/P
ython.framework/Versions/3.9/lib/python3.9/asyncio/even
ts.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/P
ython.framework/Versions/3.9/lib/python3.9/asyncio/task
s.py", line 679, in ensure_future
    raise TypeError('An asyncio.Future, a coroutine or
an awaitable is '
TypeError: An asyncio.Future, a coroutine or an awaitab
le is required
```

Is this the right way to approach this problem?
Thanks in advance.

**Comment by awestlake87** [comment]
So I think the main problem here is that you're not running a Python event loop. The Python coroutines are not spawned on the `tokio` event loop, but rather `pyo3_asyncio` expects both event loops to be running and provides the glue between them. But there are a few other problems that I think added to the confusion.

To fix your example, here's what I would recommend doing:
```rust
//! lib.rs

use pyo3::prelude::*;

#[pyclass]
struct Server {}

#[pymethods]
impl Server {
    #[new]
    fn new() -> Self {
        Self {}
    }

    /// changed signature a bit to get Python and return PyResult
    /// - PyResult translates PyErr into Python exceptions and Python calls the function exactly the
    /// same, so you should use this instead of unwrapping results.
    ///
    /// We also return PyObject here since we want to return something that Python's event loop can
    /// block on.
    fn start(&self, py: Python, test: &PyAny) -> PyResult<PyObject> {
        let f = pyo3_asyncio::into_future(test);
        // moved runtime init to #[pymodule] fn
        // let rt = tokio::runtime::Runtime::new().unwrap();

        // instead of spawning this future on the tokio event loop, we return a coroutine that
        // Python can await
        // rt.spawn(async {
        pyo3_asyncio::tokio::into_coroutine(py, async move {
            // coroutines return PyResult, so we can use ? here instead of unwrapping.
            let x = f?.await;
            match &x {
                Ok(_) => (),
                Err(v) => println!("{}", v),
            }

            // for now, we have to return a PyResult<PyObject> at the end of the coroutine. None is
            // Python's equivalent return for ()
            Ok(Python::with_gil(|py| py.None()))
        }) // remove the semicolon so we can return the coroutine
    }
}

#[pymodule]
/// export fn must have the same name as the dynamic library (whether it's roadrunner or rust_package)
pub fn rust_package(py: Python<'_>, m: &PyModule) -> PyResult<()> {
    m.add_class::<Server>()?;
    // try_init is fallible, so we should use ? here
    pyo3_asyncio::try_init(py)?;
    // initialize the tokio runtime here ('once' means that any other PyModules that use tokio can also
    // call this fn to ensure tokio runtime is initialized). If you need custom initialization and
    // are unsure of what to do here, let me know!
    pyo3_asyncio::tokio::init_multi_thread_once();

    Ok(())
}
```

```python
import asyncio
import rust_package


async def h():
    print("message from coroutine")


print("Hello world")
s = rust_package.Server()

# we want to block on the coroutine returned by s.start(_), so we get the Python
# asyncio event loop and call run_until_complete.
# 
# in your original example, you had passed h into s.start without calling it which 
# resulted in the following error:
# 
# TypeError: An asyncio.Future, a coroutine or an awaitable is required
# 
# In Python, async fns are just regular functions that return coroutines, so you
# need to call h in order to get the coroutine you pass into start().
asyncio.get_event_loop().run_until_complete(s.start(h()))
```

Most of this is my fault for not providing the docs for making `pyo3_asyncio` libraries (Sorry about that!). I'm working toward putting more examples in the docs and will hopefully have something similar to this on the README within a week or so.

**Comment by awestlake87** [comment]
`pyo3_asyncio::tokio::run_until_complete` is equivalent to the `asyncio.get_event_loop().run_until_complete(_)` line I put in the Python, so I think your second example should work the same as long as you call `h` before passing it into `s.start(_)` like I did.

It's up to you whether you want `s.start` to act as a sync or async fn.

**Comment by awestlake87** [comment]
I found some time today to make some quickstart docs for native modules. It's pretty similar to what you've already done, but if you have any suggestions, let me know!

**Comment by sansyrox** [comment]
Hi @awestlake87 , 
Thank you for the response. I was actually able to figure out an approach where I don't have to run the event loop in python.
I was finding ways to avoid running asyncio in python.

Here's what I did:

```
import rust_package

async def h():
    print("message from coroutine")


print("Hello world")
s = rust_package.Server()
s.start(h()) # here I am passing h() instead of h as h() is a coroutine and h is a function, i.e. not awaitable
```

and this is the lib.rs

```
#[pyclass]
struct Server {}

#[pymethods]
impl Server {
    #[new]
    fn new() -> Self {
        Self {}
    }

    fn start(mut self_: PyRefMut<Self>, test: &PyAny) {


        let f = pyo3_asyncio::into_future(test).unwrap();
        let rt = tokio::runtime::Runtime::new().unwrap();
        pyo3_asyncio::tokio::init(rt);
        Python::with_gil(|py| {
            pyo3_asyncio::tokio::run_until_complete(py, async move {
                tokio::time::sleep(Duration::from_secs(1)).await;
                f.await.unwrap();
                Ok(())
            })
            .unwrap();
        });
}

#[pymodule]
pub fn roadrunner(py: Python<'_>, m: &PyModule) -> PyResult<()> {
    m.add_class::<Server>()?;
    pyo3_asyncio::try_init(py);
    Ok(())
}
```

**Comment by sansyrox** [comment]
@awestlake87 , I do still have one question. Does the statement `Python::with_gil(` mean that it is firing up a new python interpreter every time it is being called? Does it make it slower then?

**Comment by awestlake87** [comment]
Great, glad to hear it's working for you!

> I do still have one question. Does the statement Python::with_gil( mean that it is firing up a new python interpreter every time it is being called? Does it make it slower then?

Essentially `Python::with_gil` is like a `Mutex` lock guard. GIL stands for Global Interpreter Lock, so calling `Python::with_gil` will lock the interpreter to the current thread before continuing. 

Python is a single-threaded language in the sense that _all Python code_ is mutually exclusive. You can have multiple Python threads, _but_ the part that makes that valuable is not actually the Python code, but the native code underneath it. So providing native code via Rust can be faster not only because Rust is faster, but because it gives you more opportunities to release the GIL and allow other threads to run _their_ Python code.

More specifically, to answer your question, `Python::with_gil` will initialize the Python interpreter only the first time it is called. Every subsequent call will just lock the GIL and allow you to call Python code, get/set attributes, basically anything you would normally do with raw Python code. If you don't need the GIL for a section of native code, it might be best to release it. `py.allow_threads` is a good way to do this temporarily without exiting the `Python::with_gil` closure.

Locking the GIL, like all mutexes, will come at a performance cost. So ideally you want to keep your calls to `Python::with_gil` to a minimum, and that also goes for your PyO3 bindings in general since crossing FFI boundaries always comes at a performance cost. That being said, this is just how native modules interact with Python, so I wouldn't worry about it too much unless you're actually trying to optimize your code.

> Thank you for the response. I was actually able to figure out an approach where I don't have to run the event loop in python.
I was finding ways to avoid running asyncio in python. As I wanted to be able to await the function in rust only and not initialise an event loop in python.

Just to clarify, `pyo3_asyncio::tokio::run_until_complete` _is_ running the Python event loop. It's basically equivalent to `asyncio.get_event_loop().run_until_complete`. PyO3 Asyncio needs the `asyncio` event loop to be running alongside `tokio` or else the conversions won't work. What you've done in your example is not a problem though, it's just more accurate to say you've turned your `start` function into a blocking function rather than an async function.

**Comment by sansyrox** [comment]
> More specifically, to answer your question, Python::with_gil will initialize the Python interpreter only the first time it is called

Thank you for this explanation.

> If you don't need the GIL for a section of native code, it might be best to release it. py.allow_threads is a good way to do this temporarily without exiting the Python::with_gil closure.

I was trying to do this with cython earlier and was driven away due to writing C like syntax. If releasing the GIL is so easy with pyo3, I may now save myself a lot of time. 
Looks like I came here to find copper but may have found a lot of bitcoins 😄 .

Thanks again!
