### ISSUE TITLE
How to return values from async functions?

### ISSUE THREAD

**Issue by shachlanAmazon** [awestlake87/pyo3-asyncio#69]
Hi, all of the examples I found were for functions that don't return values after the async computation. How can we create an async rust function that returns a value? Is there any special syntax for an async constructor?

**Comment by shachlanAmazon** [comment]
For those Interested, I found how to do that - 
```rust
  pyo3_asyncio::tokio::future_into_py(py, async move {
      let result: String = do_something().await;
      Ok(Python::with_gil(|py| result.into_py(py)))
  })
```

Keeping the issue open since I haven't found whether async constructors are possible.

**Comment by awestlake87** [comment]
I don't think async constructors are supported in Python, but what you can do is create an async static method on your class that returns an instance of the class (essentially move the async portion out of the constructor and pass the results into __init__). See [this answer](https://www.reddit.com/r/learnpython/comments/bdiyn3/comment/ekyld82/?utm_source=share&utm_medium=web2x&context=3)

You should be able to do the same thing with pyo3 using the [`#[staticmethod]`](https://pyo3.rs/main/class.html#static-methods) or [`#[classmethod]`](https://pyo3.rs/main/class.html#class-methods) attributes
