### ISSUE TITLE
py03 v17

### ISSUE THREAD

**Issue by sondrelg** [awestlake87/pyo3-asyncio#73]
Hi,

First of all, thanks for creating this great library! 

Just wanted to ask, are there any plans to upgrade to pyo3 v17 in the near future? No worries if not, just curious :slightly_smiling_face:

**Comment by awestlake87** [comment]
Yep, I noticed PyO3 17 went out recently. I am planning on upgrading it soon, but not sure of the effort involved. I'll try to take a stab at it sometime this week. It could just be as simple as bumping a few versions and touching up the docs a bit!

**Comment by sondrelg** [comment]
Thanks for letting me know! 👏 I think I spotted some deprecations, but fingers crossed it's not too bad

**Comment by jnicholls** [comment]
Perhaps we can reopen this issue and leave it open until 0.17.x support is out?

**Comment by awestlake87** [comment]
Yeah, sorry about that. I meant to get to it sooner, but I've had a busy couple of weeks. I think I should be able to get to it within a few days!

**Comment by awestlake87** [comment]
Alright, it's released now!

**Comment by cisaacson** [comment]
Thank you!

--
Cory Isaacson
http://www.coryisaacson.com
