### ISSUE TITLE
How to achieve non-blocking sleep

### ISSUE THREAD

**Issue by sondrelg** [awestlake87/pyo3-asyncio#74]
I'm having a hard time sleeping with `tokio` in a way where it doesn't block the python event loop for the duration, and after banging my head at the docs for a while I was hoping you might be able to point me in the right direction. 

I think I must be missing something simple (:crossed_fingers:), since the docs seem to strongly suggest that this is possible :slightly_smiling_face: 

I'm writing an async context manager where the `__aenter__` method contains a `tokio` sleep:

```rust
#[pyclass]
struct AsyncContextManager {}

#[pymethods]
impl AsyncContextManager {

    fn __aenter__<'a>(slf: PyRef<'_, Self>, py: Python<'a>) -> PyResult<&'a PyAny> {
        pyo3_asyncio::tokio::future_into_py(py, async move {
            tokio::time::sleep(Duration::from_secs(1)).await;
            Ok(())
        })
    }
    
    #[args(_a = "*")]
    fn __aexit__<'a>(_s: PyRef<'_, Self>, py: Python<'a>, _a: &'a PyTuple) -> PyResult<&'a PyAny> {
        future_into_py(py, async { Ok(()) })
    }
}
```

In Python, to test that the one second sleep is not blocking, I've written this test:

```python
async def _sleep():
    # This sleeps 1 second using asyncio.sleep
    await asyncio.sleep(1)

async def _context_manager_sleep():
    # This sleeps 1 second using tokio
    async with AsyncContextManager():
        pass  # the sleep is executed in __aenter__

async def test_sleep_is_non_blocking():
    tasks = [
        # Create task for context manager to sleep 1 second
        asyncio.create_task(_context_manager_sleep())),
        # And create another task to normal asyncio sleep for 1 second
        asyncio.create_task(_sleep(1)),
    ]

    # Both tasks should complete in ~1 second if thing are working correctly
    await asyncio.wait_for(asyncio.gather(*tasks), 1.05)
```

And the test is consistently coming in at 2.01s :thinking: Am I doing something obviously wrong?

**Comment by awestlake87** [comment]
I'm not able to reproduce this on Windows (haven't tried linux yet). Are you sure you're timing it in the right spot?

I had to modify your example a bit to get this to run:
```rust
// lib.rs
use pyo3::{prelude::*, types::PyTuple};

#[pyclass]
struct AsyncContextManager {}

#[pymethods]
impl AsyncContextManager {
    #[new]
    fn new() -> Self {
        AsyncContextManager {}
    }

    fn __aenter__<'a>(_s: PyRef<'_, Self>, py: Python<'a>) -> PyResult<&'a PyAny> {
        pyo3_asyncio::tokio::future_into_py(py, async move {
            tokio::time::sleep(std::time::Duration::from_secs(1)).await;
            Ok(())
        })
    }

    #[args(_a = "*")]
    fn __aexit__<'a>(_s: PyRef<'_, Self>, py: Python<'a>, _a: &'a PyTuple) -> PyResult<&'a PyAny> {
        pyo3_asyncio::tokio::future_into_py(py, async { Ok(()) })
    }
}

#[pymodule]
fn my_async_module(_py: Python, module: &PyModule) -> PyResult<()> {
    module.add_class::<AsyncContextManager>()?;
    Ok(())
}
```

```python
import asyncio
import time
from my_async_module import AsyncContextManager

async def _sleep():
    # This sleeps 1 second using asyncio.sleep
    await asyncio.sleep(1)

async def _context_manager_sleep():
    # This sleeps 1 second using tokio
    async with AsyncContextManager():
        pass  # the sleep is executed in __aenter__

async def test_sleep_is_non_blocking():
    tasks = [
        # Create task for context manager to sleep 1 second
        asyncio.create_task(_context_manager_sleep()),
        # And create another task to normal asyncio sleep for 1 second
        asyncio.create_task(_sleep()),
    ]

    # Both tasks should complete in ~1 second if thing are working correctly
    await asyncio.wait_for(asyncio.gather(*tasks), 1.05)

start = time.time()
asyncio.run(test_sleep_is_non_blocking())
end = time.time()
print(end - start)
```

```bash
> maturin develop
> python test.py
1.0099310874938965
```

**Comment by awestlake87** [comment]
I don't see anything wrong with what you're doing. There's a bit of code left out of your example I think, so my guess would be that something in the surrounding code might be slowing it down or maybe something's weird with the specific platform you're running this on. 

My computer's a bit beefy, so you might try extending the sleep durations and see if the gap closes or if it still looks like they're running one after the other.

**Comment by sondrelg** [comment]
Thanks a lot, I'll test tonight and create a demo repo if I still have issues 👍

**Comment by sondrelg** [comment]
It was a silly mistake on my end. Recreated my example from scratch and could not reproduce either. Eventually found I had stacked two sleeps deep in my test helper code :man_facepalming: Thanks again, and sorry for the false report! :clap:

**Comment by sondrelg** [comment]
(Quick bonus question, _just in case_ it's simple for you to confirm: does this seem sensible?

```rust
    fn __aenter__<'a>(_slf: PyRef<'_, Self>, py: Python<'a>) -> PyResult<&'a PyAny> {
        py.allow_threads(move || {
            thread::spawn(move || {
                tokio::runtime::Builder::new_current_thread()
                    .enable_all()
                    .build()
                    .unwrap()
                    .block_on(async {
                        tokio::time::sleep(Duration::from_secs(1)).await;
                    });
            });
        });

        future_into_py(py, async move {
            tokio::time::sleep(Duration::from_secs(1)).await;
            Ok(())
        })
    }
```
I want to run another future in a separate thread in my context manager. I'm hoping to use pyo3s `py.allow_threads` to run this in the background while python handles the returned future :slightly_smiling_face: )

**Comment by awestlake87** [comment]
My only challenge to that is that rust futures are already running on a background executor independent of python so my thought is that the extra runtime should be unnecessary unless you want two tokio runtimes for some reason

**Comment by sondrelg** [comment]
I had problems making the `__aenter__` function async since it's defined in a `#[pymethods]` impl thing :slightly_smiling_face: but you think using a tokio macro might work? That would be a lot nicer :+1:

**Comment by awestlake87** [comment]
I'm not entirely sure I understand the intent there, but I think what you're trying to do is spawn a background task that starts when `__aenter__` is called and ends(?) when `__aexit__` is called.

The way I'd recommend doing this is with `tokio::spawn`:
```rust
    fn __aenter__<'a>(&mut self, py: Python<'a>) -> PyResult<&'a PyAny> {
        self.join_hdl = Some(tokio::spawn(async {
            tokio::time::sleep(Duration::from_secs(1)).await;
        });

        future_into_py(py, async move {
            tokio::time::sleep(Duration::from_secs(1)).await;
            Ok(())
        })
    }

    #[args(_a = "*")]
    fn __aexit__<'a>(&mut self, py: Python<'a>, _a: &'a PyTuple) -> PyResult<&'a PyAny> {
        let mut join_hdl = self.join_hdl.take();

        pyo3_asyncio::tokio::future_into_py(py, async move { 
            join_hdl.await.unwrap();
            Ok(()) 
        })
    }
```

Disclaimer: I haven't actually compiled and ran this, I'm just writing it from what I remember about these libraries so it's very possible it has compile errors. Something like this is definitely possible though.

**Comment by sondrelg** [comment]
This looks a lot nicer. Unfortunately, looks like it causes a 
``` 
pyo3_runtime.PanicException: there is no reactor running, must be called from the context of a Tokio 1.x runtime
```
I think that's how I ended up creating an entire runtime from scratch - but maybe there's a better way :slightly_smiling_face: I'll try to read up on it a bit. Thanks again!

**Comment by awestlake87** [comment]
You're right, my bad. I actually compiled and ran this snippet:
```rust
#[pyclass]
struct AsyncContextManager {
    join_hdl: Option<tokio::task::JoinHandle<()>>,
}

#[pymethods]
impl AsyncContextManager {
    #[new]
    fn new() -> Self {
        AsyncContextManager { join_hdl: None }
    }

    fn __aenter__<'a>(&mut self, py: Python<'a>) -> PyResult<&'a PyAny> {
        self.join_hdl = Some(pyo3_asyncio::tokio::get_runtime().spawn(async {
            tokio::time::sleep(std::time::Duration::from_secs(1)).await;
        }));

        pyo3_asyncio::tokio::future_into_py(py, async move {
            tokio::time::sleep(std::time::Duration::from_secs(1)).await;
            Ok(())
        })
    }

    #[args(_a = "*")]
    fn __aexit__<'a>(&mut self, py: Python<'a>, _a: &'a PyTuple) -> PyResult<&'a PyAny> {
        let join_hdl = self.join_hdl.take();

        pyo3_asyncio::tokio::future_into_py(py, async move {
            if let Some(join_hdl) = join_hdl {
                join_hdl.await.unwrap();
            }
            Ok(())
        })
    }
}
```

The main difference being instead of `tokio::spawn`, I get a reference to PyO3's tokio executor with `pyo3_asyncio::tokio::get_runtime()` and call spawn on it. You can use `tokio::spawn` on tokio's threads, but since `__aenter__` is called on a Python thread, you need have a reference to the executor in order to spawn a future on it.

**Comment by sondrelg** [comment]
awesome! 👏
