### ISSUE TITLE
Can't work with PyDict within async block

### ISSUE THREAD

**Issue by ifeanyipossibilities** [awestlake87/pyo3-asyncio#75]
Please help me, 😳, am trying to work with PyDict within the async block and am getting the errors below.

```rust
use pyo3::prelude::*;
use pyo3::types::{PyDict, PyTuple};

#[pyfunction]
fn rust_sleep(py: Python) -> PyResult<&PyAny> {
    let mut dict = PyDict::new(py);
    pyo3_asyncio::tokio::future_into_py(py, async {
       
       
        tokio::time::sleep(std::time::Duration::from_secs(1)).await;
        dict.set_item("duration", "1 seconds".to_string());
        
        Ok(dict)
    })
}



#[pymodule]
fn my_async_module(py: Python, m: &PyModule) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(rust_sleep, m)?)?;
    Ok(())
}

```

error[E0277]: `UnsafeCell<PyObject>` cannot be shared between threads safely                                                                                
   --> src/lib.rs:64:45
    |
64  |       pyo3_asyncio::tokio::future_into_py(py, async {
    |  _____-----------------------------------_____^
    | |     |
    | |     required by a bound introduced by this call
65  | |        
66  | |        
67  | |         tokio::time::sleep(std::time::Duration::from_secs(1)).await;
...   |
70  | |         Ok(dict)
71  | |     })
    | |_____^ `UnsafeCell<PyObject>` cannot be shared between threads safely
    |
    = help: within `&PyDict`, the trait `Sync` is not implemented for `UnsafeCell<PyObject>`
    = note: required because it appears within the type `pyo3::PyAny`
    = note: required because it appears within the type `PyDict`
    = note: required because it appears within the type `&PyDict`
    = note: required for `&&PyDict` to implement `std::marker::Send`
note: required because it's used within this `async` block
   --> src/lib.rs:64:51
    |
64  |       pyo3_asyncio::tokio::future_into_py(py, async {
    |  ___________________________________________________^
65  | |        
66  | |        
67  | |         tokio::time::sleep(std::time::Duration::from_secs(1)).await;
...   |
70  | |         Ok(dict)
71  | |     })
    | |_____^
note: required by a bound in `pyo3_asyncio::tokio::future_into_py`
   --> /Users/ifeanyi/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-asyncio-0.16.0/src/tokio.rs:335:39
    |
335 |     F: Future<Output = PyResult<T>> + Send + 'static,
    |                                       ^^^^ required by this bound in `pyo3_asyncio::tokio::future_into_py`

error: aborting due to previous error; 4 warnings emittedtest_project_rs                                                                                          

For more information about this error, try `rustc --explain E0277`.

error: could not compile `test_project_rs` due to 2 previous errors; 4 warnings emitted
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit status: 101": `"cargo" "rustc" "--message-format" "json" "--lib" "--" "-C" "link-arg=-undefined" "-C" "link-arg=dynamic_lookup" "-C" "link-args=-Wl,-install_name,@rpath/test_project_rs.cpython-39-darwin.so"`

**Comment by awestlake87** [comment]
I think you're getting this error because you're trying to return a `&'py PyDict`. The `'py' lifetime is tied to the GIL guard, and it doesn't want you to send it between threads.

You can get around this using pyo3's `Py<T>`:

```rust
#[pyfunction]
fn rust_sleep(py: Python) -> PyResult<&PyAny> {
    let dict: Py<PyDict> = PyDict::new(py).into_py(py);

    pyo3_asyncio::tokio::future_into_py(py, async {
        tokio::time::sleep(std::time::Duration::from_secs(1)).await;

        Python::with_gil(|py| {
            dict.as_ref(py)
                .set_item("duration", "1 seconds".to_string())
        })?;

        Ok(dict)
    })
}
```

**Comment by ifeanyipossibilities** [comment]
Thank you 

> I think you're getting this error because you're trying to return a `&'py PyDict`. The `'py` lifetime is tied to the GIL guard, and it doesn't want you to send it between threads.
> 
> You can get around this using pyo3's `Py<T>`:
> 
> ```rust
> #[pyfunction]
> fn rust_sleep(py: Python) -> PyResult<&PyAny> {
>     let dict: Py<PyDict> = PyDict::new(py).into_py(py);
> 
>     pyo3_asyncio::tokio::future_into_py(py, async {
>         tokio::time::sleep(std::time::Duration::from_secs(1)).await;
> 
>         Python::with_gil(|py| {
>             dict.as_ref(py)
>                 .set_item("duration", "1 seconds".to_string())
>         })?;
> 
>         Ok(dict)
>     })
> }
> ```

Thank you compiled.
