### ISSUE TITLE
check whether Future is done before setting result or exception to avoid InvalidStateExceptions

### ISSUE THREAD

**Issue by decathorpe** [awestlake87/pyo3-asyncio#77]
In my project (<https://github.com/decathorpe/mitmproxy_wireguard>), which uses pyo3-asyncio/tokio, sometimes the Python code which calls into the module implemented with PyO3 hits an `InvalidStateException` that's raised within Python's asyncio module.

It looks like this happens when a Future is cancelled from the Python side before it yields from the Rust side, and since there are no checks before pyo3-asyncio sets the result of a `Future`, this causes an `InvalidStateException`, because calling `set_result` and `set_exception` on a `Future` *after* it is done or was cancelled is a problem.

I wasn't able to come up with a simple reproducer, but looking at the docs of the Python `asyncio` module, it seems clear that any calls of `Future.set_result` and `Future.set_exception` should be preceded by a call to `Future.done()`, and only if that method returns `False`, then the methods can be called. Otherwise the callback should return early, if I understand correctly.

I attempted to implement this by replacing the plain `Future.set_result` and `Future.set_exception` callbacks that are scheduled in the `set_result` function with functions that check whether the future is "done" yet before setting the result / exception ... however, I couldn't figure out how to pass a function that's implemented in Rust as an argument to `call_soon_threadsafe`. I think something like this should avoid calling the `asyncio` API in a way that raises `InvalidStateException`s:

https://github.com/decathorpe/pyo3-asyncio/commit/1d09374a361ca60bef090e73ef7ccfb4d96835c1

**Comment by decathorpe** [comment]
I forgot to mention: I see that there are *some* checks whether a future is cancelled before the `set_result` function is called. But since we're still getting `InvalidStateException`s, I think this code might be prone to race conditions unless both the check and the `set_result` / `set_exception` call are submitted *together* to `call_soon_threadsafe`, instead of being called separately, potentially getting scheduled to run at different points im time?

**Comment by awestlake87** [comment]
Thanks @decathorpe and @mhils for the PRs! (and sorry for the delayed response, I just got back from a business trip).

As long as all the existing tests pass, I don't see any reason not to merge it. I should be able to evaluate these and merge in a couple of days, so hopefully we can include it in the 0.17 release. 

Race conditions are really hard to test, so it's not surprising that you're having trouble reproducing it with a smaller example (I'm assuming you might be in the same boat in terms of testability, @mhils?) 

Are either of you guys able to share a project or repo that has this issue? I might take a stab at creating a stress test based off of it, but I've honestly never run into it myself. No worries if it's private code, though.

**Comment by decathorpe** [comment]
We're working on the same projects - mitmproxy_wireguard (with Python / PyO3) and mitmproxy (Python). The problem happened in integration tests in mitmproxy, where we use mitmproxy_wireguard.

I think the easiest way to reproduce the InvalidStateError might be:

1. create a Python coroutine that just runs tokio::time::sleep(1) in Rust
2. await this coroutine in async Python code
3. cancel the future from the Python side *just before it yields*

The race condition can then happen if the future is cancelled from the Python side between the "has this been cancelled" check in pyo3-asyncio's `set_result` and whenever the coroutine that actually calls `Future.set_value` is scheduled and run.

I can try to create a simple reproducer ...

**Comment by decathorpe** [comment]
Here's a bare-bones project with a reproducer:
https://github.com/decathorpe/pyo3-asyncio-issue-77-test-project

Letting test.py loop for a few seconds should trigger InvalidStateError.

**Comment by awestlake87** [comment]
I went ahead and merged #78 and incorporated the reproducer as a regression test. Feel free to reopen this issue if you see any issues with it!
